require("Classes")
-- MAKE SURE THESE VALUES MATCH SQL FILE
local VENDOR_TIER3_WARRIOR = 310000
local VENDOR_TIER3_PALADIN = 320000
local VENDOR_TIER3_HUNTER = 330000
local VENDOR_TIER3_ROGUE = 340000
local VENDOR_TIER3_PRIEST = 350000
local VENDOR_TIER3_SHAMAN = 370000
local VENDOR_TIER3_MAGE = 380000
local VENDOR_TIER3_WARLOCK = 390000
local VENDOR_TIER3_DRUID = 311000
VENDOR_TIER3_ITEMS = 312000

---@type { [number]: number }
TIER3_CLASS_VENDORS = {
    [CLASS_WARRIOR] = VENDOR_TIER3_WARRIOR,
    [CLASS_PALADIN] = VENDOR_TIER3_PALADIN,
    [CLASS_HUNTER] = VENDOR_TIER3_HUNTER,
    [CLASS_ROGUE] = VENDOR_TIER3_ROGUE, 
    [CLASS_PRIEST] = VENDOR_TIER3_PRIEST,
    [CLASS_SHAMAN] = VENDOR_TIER3_SHAMAN, 
    [CLASS_MAGE] = VENDOR_TIER3_MAGE, 
    [CLASS_WARLOCK] = VENDOR_TIER3_WARLOCK,
    [CLASS_DRUID] = VENDOR_TIER3_DRUID,
}