require("Classes")
-- MAKE SURE THESE VALUES MATCH SQL FILE
local VENDOR_TIER2_WARRIOR = 210000
local VENDOR_TIER2_PALADIN = 220000
local VENDOR_TIER2_HUNTER = 230000
local VENDOR_TIER2_ROGUE = 240000
local VENDOR_TIER2_PRIEST = 250000
local VENDOR_TIER2_SHAMAN = 270000
local VENDOR_TIER2_MAGE = 280000
local VENDOR_TIER2_WARLOCK = 290000
local VENDOR_TIER2_DRUID = 211000
VENDOR_TIER2_ITEMS = 212000

---@type { [number]: number }
TIER2_CLASS_VENDORS = {
    [CLASS_WARRIOR] = VENDOR_TIER2_WARRIOR,
    [CLASS_PALADIN] = VENDOR_TIER2_PALADIN,
    [CLASS_HUNTER] = VENDOR_TIER2_HUNTER,
    [CLASS_ROGUE] = VENDOR_TIER2_ROGUE, 
    [CLASS_PRIEST] = VENDOR_TIER2_PRIEST,
    [CLASS_SHAMAN] = VENDOR_TIER2_SHAMAN, 
    [CLASS_MAGE] = VENDOR_TIER2_MAGE, 
    [CLASS_WARLOCK] = VENDOR_TIER2_WARLOCK,
    [CLASS_DRUID] = VENDOR_TIER2_DRUID,
}