require("Classes")
-- MAKE SURE THESE VALUES MATCH SQL FILE
local VENDOR_TIER1_WARRIOR = 110000
local VENDOR_TIER1_PALADIN = 120000
local VENDOR_TIER1_HUNTER = 130000
local VENDOR_TIER1_ROGUE = 140000
local VENDOR_TIER1_PRIEST = 150000
local VENDOR_TIER1_SHAMAN = 170000
local VENDOR_TIER1_MAGE = 180000
local VENDOR_TIER1_WARLOCK = 190000
local VENDOR_TIER1_DRUID = 111000
VENDOR_TIER1_ITEMS = 112000

---@type { [number]: number }
TIER1_CLASS_VENDORS = {
    [CLASS_WARRIOR] = VENDOR_TIER1_WARRIOR,
    [CLASS_PALADIN] = VENDOR_TIER1_PALADIN,
    [CLASS_HUNTER] = VENDOR_TIER1_HUNTER,
    [CLASS_ROGUE] = VENDOR_TIER1_ROGUE,
    [CLASS_PRIEST] = VENDOR_TIER1_PRIEST,
    [CLASS_SHAMAN] = VENDOR_TIER1_SHAMAN,
    [CLASS_MAGE] = VENDOR_TIER1_MAGE,
    [CLASS_WARLOCK] = VENDOR_TIER1_WARLOCK,
    [CLASS_DRUID] = VENDOR_TIER1_DRUID,
}
